#!/usr/bin/env sh

# 👉 窗口布局与摆放
yabai -m config layout bsp
yabai -m config window_placement second_child

# 👉 外边距与窗口间距
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# 👉 鼠标行为设定
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m mouse_drop_action swap

# 👉 外部 Bar（例如 SketchyBar）支持
yabai -m config external_bar all:32:0

# add these lines to the bottom of your yabairc file
# they're needed to trigger a custom event in sketchybar that we will later define in sketchybarrc

yabai -m signal --add event=window_created action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_change &> /dev/null"
